name: Deploy to Vercel

on:
  push:
    branches:
      - master  # ou main, dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Fazer deploy na Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --token $VERCEL_TOKEN --confirm
