name: Sync Fork with Upstream (PRIVATE - master)

on:
  schedule:
    - cron: '0 3 * * *'  # Executa diariamente às 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork (master)
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add and fetch upstream (PRIVATE)
        env:
          TOKEN: ${{ secrets.UPSTREAM_TOKEN }}
        run: |
          echo "✅ Tentando acessar o repositório da organização..."
          git remote remove upstream || true
          git remote add upstream https://x-access-token:${TOKEN}@github.com/EmitSoft/EmitSoft-Web-Site.git

          git ls-remote upstream || (echo "❌ Token inválido ou sem permissão. Verifique o segredo UPSTREAM_TOKEN." && exit 1)

          git fetch upstream
          git reset --hard upstream/master

      - name: Push changes to your fork
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git master --force
